"""add inventory is_global

Revision ID: 499c93c21e31
Revises: 5c2b80c49fc9
Create Date: 2026-09-28 21:43:08.304478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499c93c21e31'
down_revision: Union[str, Sequence[str], None] = '5c2b80c49fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('is_global', sa.Boolean(), nullable=False,
                                         server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'is_global')
    # ### end Alembic commands ###
