"""nullable security profile label

Revision ID: 713db4dd6251
Revises: 499c93c21e31
Create Date: 2026-09-29 02:02:04.173385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713db4dd6251'
down_revision: Union[str, Sequence[str], None] = '499c93c21e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_profiles', 'label',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Label-less profiles would violate NOT NULL — backfill with the
    # username, which is what the UI displays for them anyway
    op.execute("UPDATE security_profiles SET label = username "
               "WHERE label IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_profiles', 'label',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
