"""add_ldap

Revision ID: a19370a56122
Revises: 174eebf39301
Create Date: 2026-04-26 09:00:43.407801

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a19370a56122'
down_revision: Union[str, Sequence[str], None] = '174eebf39301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('ldap_servers',
	                sa.Column('id', sa.Uuid(), nullable=False),
	                sa.Column('name', sa.String(length=64), nullable=False),
	                sa.Column('host', sa.String(length=255), nullable=False),
	                sa.Column('port', sa.Integer(), nullable=False),
	                sa.Column('base_dn', sa.String(length=255), nullable=False),
	                sa.Column('cn_identifier', sa.String(length=64),
	                          nullable=False),
	                sa.Column('bind_type', sa.String(length=20),
	                          nullable=False),
	                sa.Column('bind_dn', sa.String(length=255), nullable=True),
	                sa.Column('bind_password', sa.String(length=255),
	                          nullable=True),
	                sa.Column('use_ssl', sa.Boolean(), nullable=False),
	                sa.Column('is_active', sa.Boolean(), nullable=False),
	                sa.PrimaryKeyConstraint('id')
	                )
	op.create_table('ldap_groups',
	                sa.Column('id', sa.Uuid(), nullable=False),
	                sa.Column('group_dn', sa.String(length=512),
	                          nullable=False),
	                sa.Column('label', sa.String(length=128), nullable=False),
	                sa.Column('role', sa.String(length=40), nullable=False),
	                sa.Column('is_active', sa.Boolean(), nullable=False),
	                sa.Column('ldap_server_id', sa.Uuid(), nullable=False),
	                sa.ForeignKeyConstraint(['ldap_server_id'],
	                                        ['ldap_servers.id'],
	                                        ondelete='CASCADE'),
	                sa.PrimaryKeyConstraint('id')
	                )
	op.add_column('users',
	              sa.Column('auth_type', sa.String(length=20), nullable=False,
	                        server_default='local'))
	op.alter_column('users', 'auth_type', server_default=None)
	op.add_column('users',
	              sa.Column('ldap_server_id', sa.Uuid(), nullable=True))
	op.alter_column('users', 'password_hash',
	                existing_type=sa.VARCHAR(length=255),
	                nullable=True)
	op.create_foreign_key(None, 'users', 'ldap_servers', ['ldap_server_id'],
	                      ['id'], ondelete='SET NULL')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, 'users', type_='foreignkey')
	op.alter_column('users', 'password_hash',
	                existing_type=sa.VARCHAR(length=255),
	                nullable=False)
	op.drop_column('users', 'ldap_server_id')
	op.drop_column('users', 'auth_type')
	op.drop_table('ldap_groups')
	op.drop_table('ldap_servers')
	# ### end Alembic commands ###
