"""The audit log's vocabulary: every action an audit row can record. The
values are what the audit_log table, the admin's audit page and analytics,
the tests and Grafana's dashboards see - never change one; add a member for
a new action."""
from enum import StrEnum


class AuditAction(StrEnum):
	"""What an audit row says happened (audit_log.action)."""
	# signing in and the account itself
	AUTH_LOGIN = "auth.login"
	AUTH_LOGOUT = "auth.logout"
	AUTH_PASSWORD_OK = "auth.password_ok"
	AUTH_PASSWORD_CHANGE = "auth.password_change"
	AUTH_REGISTER = "auth.register"
	AUTH_SESSION_EXPIRED = "auth.session_expired"
	# an admin on users (user.<action> / user.bulk_<action>: admin_users.USER_ACTIONS)
	USER_CREATED = "user.created"
	USER_RESET_PASSWORD = "user.reset_password"
	USER_APPROVE = "user.approve"
	USER_ENABLE = "user.enable"
	USER_DISABLE = "user.disable"
	USER_PROMOTE = "user.promote"
	USER_DEMOTE = "user.demote"
	USER_DELETE = "user.delete"
	USER_RESET_2FA = "user.reset_2fa"
	USER_TERMINATE_SESSION = "user.terminate_session"
	USER_BULK_APPROVE = "user.bulk_approve"
	USER_BULK_ENABLE = "user.bulk_enable"
	USER_BULK_DISABLE = "user.bulk_disable"
	USER_BULK_PROMOTE = "user.bulk_promote"
	USER_BULK_DEMOTE = "user.bulk_demote"
	USER_BULK_DELETE = "user.bulk_delete"
	USER_BULK_RESET_2FA = "user.bulk_reset_2fa"
	USER_BULK_TERMINATE_SESSION = "user.bulk_terminate_session"
	ADMIN_SESSION_KICK = "admin.session_kick"
	# LDAP
	ADMIN_LDAP_SERVER_SAVE = "admin.ldap_server_save"
	ADMIN_LDAP_SERVER_DELETE = "admin.ldap_server_delete"
	ADMIN_LDAP_IMPORT = "admin.ldap_import"
	ADMIN_LDAP_GROUP_TOGGLE = "admin.ldap_group_toggle"
	ADMIN_LDAP_GROUP_DELETE = "admin.ldap_group_delete"
	# the inventory and what goes with it
	INVENTORY_CREATE = "inventory.create"
	INVENTORY_EDIT = "inventory.edit"
	INVENTORY_DELETE = "inventory.delete"
	INVENTORY_GLOBALIZE = "inventory.globalize"
	INVENTORY_LOCALIZE = "inventory.localize"
	INVENTORY_ATTRIBUTES = "inventory.attributes"
	INVENTORY_IMPORT_CSV = "inventory.import_csv"
	INVENTORY_BULK_ASSIGN = "inventory.bulk_assign"
	SECURITY_PROFILE_CREATE = "security_profile.create"
	SECURITY_PROFILE_EDIT = "security_profile.edit"
	SECURITY_PROFILE_DELETE = "security_profile.delete"
	MAPPING_CREATE = "mapping.create"
	MAPPING_EDIT = "mapping.edit"
	MAPPING_DELETE = "mapping.delete"
	MAPPING_BULK_ASSIGN = "mapping.bulk_assign"
	PROPERTY_CREATE = "property.create"
	PROPERTY_EDIT = "property.edit"
	PROPERTY_DELETE = "property.delete"
	# rollouts
	ROLLOUT_START = "rollout.start"
	ROLLOUT_CANCEL = "rollout.cancel"
	ROLLOUT_ROLLBACK = "rollout.rollback"
	# the server
	SETTINGS_UPDATE = "settings.update"
	SETTINGS_RESET = "settings.reset"
	SETTINGS_PORT_CONFIRMED = "settings.port_confirmed"
	SERVER_RESTART = "server.restart"
	SERVER_REDIS_SWITCHED = "server.redis_switched"
	SERVER_CERTIFICATE_UPLOADED = "server.certificate_uploaded"
	SERVER_CERTIFICATE_GENERATED = "server.certificate_generated"
	BACKUP_CREATED = "backup.created"
	BACKUP_DOWNLOADED = "backup.downloaded"
	BACKUP_DELETED = "backup.deleted"
	BACKUP_FAILED = "backup.failed"
	BACKUP_RESTORED = "backup.restored"
	DATABASE_PREPARED = "database.prepared"
	DATABASE_PREPARE_FAILED = "database.prepare_failed"
	DATABASE_MOVE_STARTED = "database.move_started"
	DATABASE_MOVED = "database.moved"
	DATABASE_MOVE_FAILED = "database.move_failed"
	DATABASE_MOVE_CANCELLED = "database.move_cancelled"
